version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  m1:
    build:
      context: ./provider
    ports:
      - "4001:4001"
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  m2:
    build:
      context: ./receiver
    ports:
      - "4002:4002"
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge